<a href="https://colab.research.google.com/github/sagarikaraje/Natural-Language-Processing/blob/main/Lab%20Assignments/Assignment%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import nltk as nltk
# import gensim as gs
# import spacy as sp
# import textblob as tb
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
from string import punctuation
from nltk.tokenize import word_tokenize
from nltk.stem import LancasterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
df= pd.read_csv('/content/drive/MyDrive/spam.csv')

In [ ]:
df

v1                                                 v2   v3   V4   V5
0      ham  Go until jurong point, crazy.. Available only ...  NaN  NaN  NaN
1      ham                      Ok lar... Joking wif u oni...  NaN  NaN  NaN
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...  NaN  NaN  NaN
3      ham  U dun say so early hor... U c already then say...  NaN  NaN  NaN
4      ham  Nah I don't think he goes to usf, he lives aro...  NaN  NaN  NaN
...    ...                                                ...  ...  ...  ...
5567  spam  This is the 2nd time we have tried 2 contact u...  NaN  NaN  NaN
5568   ham              Will Ì_ b going to esplanade fr home?  NaN  NaN  NaN
5569   ham  Pity, * was in mood for that. So...any other s...  NaN  NaN  NaN
5570   ham  The guy did some bitching but I acted like i'd...  NaN  NaN  NaN
5571   ham                         Rofl. Its true to its name  NaN  NaN  NaN

[5572 rows x 5 columns]

In [ ]:
l= df.columns

In [ ]:
l

Index(['v1', 'v2', 'v3', 'V4', 'V5'], dtype='object')

In [ ]:
for i in range(len(l)):

  a= l[i]
  print('column: ',i,'Null vals',df[a].isnull().sum()/df.shape[0] * 100)

column:  0 Null vals 0.0
column:  1 Null vals 0.0
column:  2 Null vals 99.10265613783201
column:  3 Null vals 99.78463747307968
column:  4 Null vals 99.89231873653985


In [ ]:
df.shape

(5572, 5)

In [ ]:
df.drop(columns= ['v3', 'V4', 'V5'], axis= 1, inplace= True)

In [ ]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.shape

(5572, 2)

In [ ]:
df['v2']

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: v2, Length: 5572, dtype: object

In [ ]:
# Lowering the letters

df['v2'] = df['v2'].str.lower()

In [ ]:
df.head()

v1                                                 v2
0   ham  go until jurong point, crazy.. available only ...
1   ham                      ok lar... joking wif u oni...
2  spam  free entry in 2 a wkly comp to win fa cup fina...
3   ham  u dun say so early hor... u c already then say...
4   ham  nah i don't think he goes to usf, he lives aro...

In [ ]:
groups= df['v1']

In [ ]:
groups

0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: v1, Length: 5572, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

enc= LabelEncoder()

df['v1']= enc.fit_transform(df['v1'])

print(df['v1'])

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: v1, Length: 5572, dtype: int64


In [ ]:
value_counts= df['v1'].value_counts()

In [ ]:
value_counts/df['v1'].shape[0] * 100

0    86.593683
1    13.406317
Name: v1, dtype: float64

SINCE THE DATASET IS IMBALANCED WE WILL TAKE F-SCORE TO DETERMINE THE BEST ALGORITHM FOR THE CLASSIFIACTION.

In [ ]:
# list containing the dependent variables

y_l= df['v1'].to_list()

print(y_l)

[0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 

In [ ]:
len(y_l)

5572

Preprocessing for the text classification

In [ ]:
from string import punctuation
from nltk.corpus import stopwords

In [ ]:
stuff_to_be_removed= list(stopwords.words('english'))+ list(punctuation)


from nltk.tokenize import word_tokenize
from nltk.stem import LancasterStemmer

stemmer = LancasterStemmer()

corpus = df['v2'].tolist()
len(corpus)


5572

In [ ]:
corpus

['go until jurong point, crazy.. available only in bugis n great world la e buffet... cine there got amore wat...',
 'ok lar... joking wif u oni...',
 "free entry in 2 a wkly comp to win fa cup final tkts 21st may 2005. text fa to 87121 to receive entry question(std txt rate)t&c's apply 08452810075over18's",
 'u dun say so early hor... u c already then say...',
 "nah i don't think he goes to usf, he lives around here though",
 "freemsg hey there darling it's been 3 week's now and no word back! i'd like some fun you up for it still? tb ok! xxx std chgs to send, å£1.50 to rcv",
 'even my brother is not like to speak with me. they treat me like aids patent.',
 "as per your request 'melle melle (oru minnaminunginte nurungu vettam)' has been set as your callertune for all callers. press *9 to copy your friends callertune",
 'winner!! as a valued network customer you have been selected to receivea å£900 prize reward! to claim call 09061701461. claim code kl341. valid 12 hours only.',
 'had y

In [ ]:
final_corpus = []
for i in range(len(corpus)):
  word = word_tokenize(corpus[i].lower())
  word = [stemmer.stem(y) for y in word if y not in stuff_to_be_removed]
  j = " ".join(word)
  final_corpus.append(j)

In [ ]:
final_corpus

['go jurong point crazy.. avail bug n gre world la e buffet ... cin got am wat ...',
 'ok lar ... jok wif u on ...',
 "fre entry 2 wkly comp win fa cup fin tkts 21st may 2005. text fa 87121 receiv entry quest std txt rat c 's apply 08452810075over18 's",
 'u dun say ear hor ... u c already say ...',
 "nah n't think goe usf liv around though",
 "freemsg hey darl 's 3 week 's word back 'd lik fun stil tb ok xxx std chgs send å£1.50 rcv",
 'ev broth lik speak tre lik aid pat',
 "per request 'melle mel oru minnaminungint nurungu vettam set callertun cal press *9 cop friend callertun",
 'win valu network custom select receive å£900 priz reward claim cal 09061701461. claim cod kl341 valid 12 hour',
 'mobl 11 month u r entitl upd latest colo mobl camer fre cal mobl upd co fre 08002986030',
 "'m gon na hom soon n't want talk stuff anym tonight k 've cri enough today",
 'six chant win cash 100 20,000 pound txt csh11 send 87575. cost 150p/day 6days 16+ tsandc apply reply hl 4 info',
 'urg 1 week

In [ ]:
y_l

[0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,


In [ ]:
newdf = pd.DataFrame(final_corpus)
newdf['label'] = y_l

newdf.columns=['sentence','label']

In [ ]:
newdf

sentence  label
0     go jurong point crazy.. avail bug n gre world ...      0
1                           ok lar ... jok wif u on ...      0
2     fre entry 2 wkly comp win fa cup fin tkts 21st...      1
3             u dun say ear hor ... u c already say ...      0
4               nah n't think goe usf liv around though      0
...                                                 ...    ...
5567  2nd tim tri 2 contact u. u å£750 pound priz 2 ...      1
5568                         ì_ b going esplanad fr hom      0
5569                              pity mood ... suggest      0
5570  guy bitch act lik 'd interest buy someth els n...      0
5571                                       rofl tru nam      0

[5572 rows x 2 columns]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer


tfidf = TfidfVectorizer()
vector = tfidf.fit_transform(newdf['sentence'])


x_train = vector.toarray()
y_train= newdf['label']

In [ ]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
y_train

0       0
1       0
2       1
3       0
4       0
       ..
5567    1
5568    0
5569    0
5570    0
5571    0
Name: label, Length: 5572, dtype: int64

In [ ]:
from sklearn.naive_bayes import MultinomialNB
ab = MultinomialNB() #MULTINOMIAL NAIVE BAYES

ab.fit(x_train,y_train)
ypred = ab.predict(x_train)


from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

print('Accuracu =',accuracy_score(y_train,ypred))

print('\n', confusion_matrix(y_train,ypred))

print('\n', classification_report(y_train,ypred))

Accuracu = 0.9822325915290739

 [[4825    0]
 [  99  648]]

               precision    recall  f1-score   support

           0       0.98      1.00      0.99      4825
           1       1.00      0.87      0.93       747

    accuracy                           0.98      5572
   macro avg       0.99      0.93      0.96      5572
weighted avg       0.98      0.98      0.98      5572



In [ ]:
from sklearn.metrics import f1_score

score = f1_score(y_train, ypred, average='macro')
print("Test F1_Score: MULTINOMIAL NAIVE BAYES  {}".format(score))

Test F1_Score: MULTINOMIAL NAIVE BAYES  0.9594386851918641


In [ ]:
from sklearn.naive_bayes import GaussianNB

gnb= GaussianNB()

gnb.fit(x_train,y_train)
ypred_1 = gnb.predict(x_train)


from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

print('Accuracu =',accuracy_score(y_train,ypred_1))

print('\n', confusion_matrix(y_train,ypred_1))

print('\n', classification_report(y_train,ypred_1))

Accuracu = 0.8955491744436468

 [[4243  582]
 [   0  747]]

               precision    recall  f1-score   support

           0       1.00      0.88      0.94      4825
           1       0.56      1.00      0.72       747

    accuracy                           0.90      5572
   macro avg       0.78      0.94      0.83      5572
weighted avg       0.94      0.90      0.91      5572



In [ ]:
score1 = f1_score(y_train, ypred_1, average='macro')
print("Test F1_Score: GaussianNB {}".format(score1))

Test F1_Score: GaussianNB 0.8277357206055214


In [ ]:
from sklearn.ensemble import RandomForestClassifier

rfc= RandomForestClassifier()

rfc.fit(x_train,y_train)
ypred_2 = rfc.predict(x_train)


from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

print('Accuracu =',accuracy_score(y_train,ypred_2))

print('\n', confusion_matrix(y_train,ypred_2))

print('\n', classification_report(y_train,ypred_2))

Accuracu = 1.0

 [[4825    0]
 [   0  747]]

               precision    recall  f1-score   support

           0       1.00      1.00      1.00      4825
           1       1.00      1.00      1.00       747

    accuracy                           1.00      5572
   macro avg       1.00      1.00      1.00      5572
weighted avg       1.00      1.00      1.00      5572



In [ ]:
score2 = f1_score(y_train, ypred_2, average='macro')
print("Test F1_Score: Random Forest  {}".format(score2))

Test F1_Score: Random Forest  1.0


Answer

Since the F1 Score for Random Forest is 1 which is the highest as compared to other two algorithms.

Therefore it is the best algorithm for the classification.